### ISSUE TITLE
ImportError for module 'zstandard' when loading pipeline in warrior

### ISSUE THREAD

**Issue by foghawk** [ArchiveTeam/tencent-weibo-grab#1]
Log:
```
2020-09-19 19:43:09,828 - seesaw.warrior - DEBUG - Update warrior hq.
2020-09-19 19:43:09,829 - seesaw.warrior - DEBUG - Warrior ID '17878'.
2020-09-19 19:43:10,489 - seesaw.warrior - DEBUG - Select project tencent-weibo
2020-09-19 19:43:10,489 - seesaw.warrior - DEBUG - Start selected project tencent-weibo
(reinstall=False)
2020-09-19 19:43:10,489 - seesaw.warrior - DEBUG - Install project tencent-weibo
2020-09-19 19:43:10,489 - seesaw.warrior - DEBUG - git clone
2020-09-19 19:43:10,935 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/tencent-weibo'...
2020-09-19 19:43:10,936 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/tencent-weibo'...
2020-09-19 19:43:10,936 - seesaw.warrior - DEBUG - Result of the install process: True
2020-09-19 19:43:10,936 - seesaw.warrior - DEBUG - Clone project tencent-weibo /home/warrior/projects/tencent-weibo
2020-09-19 19:43:10,938 - seesaw.warrior - DEBUG - Cloning version 9bae5f9
2020-09-19 19:43:11,011 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/tencent-weibo-9bae5f9/pipeline.py
2020-09-19 19:43:11,011 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2020-09-19 19:43:11,011 - seesaw.warrior - DEBUG - Executing pipeline
2020-09-19 19:43:11,120 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context) File "<string>", line 29, in <module>
ImportError: No module named 'zstandard'
2020-09-19 19:43:11,120 - seesaw.warrior - WARNING - Project tencent-weibo did not install correctly and we're ignoring this problem.
```

Project or warrior environment?

**Comment by Arkiver2** [comment]
This currently doesn't work in the Warrior, I'll update documentation.
